
-- DDL

-- CRIAR UM BANCO
CREATE DATABASE Exercicio_1_4;

-- USAR O BANCO CRIADO
USE Exercicio_1_4;

-- CRIAR TABELAS
-- UNIQUE ( CAMPO EXCLUSIVO QUE NÃO PODE SER REPETIDO. EX: CPF, CNH, EMAIL ).
-- NOT NULL ( CAMPO QUE DEVE SER PREENCHIDO OBRIGATORIAMENTE ).
CREATE TABLE Artistas
(
	IdArtista INT PRIMARY KEY IDENTITY,
	Nome VARCHAR(20) NOT NULL,
)

CREATE TABLE Estilos
(
	IdEstilo INT PRIMARY KEY IDENTITY,
	Nome VARCHAR(20) NOT NULL
)

CREATE TABLE Usuarios
(
	IdUsuario INT PRIMARY KEY IDENTITY,
	Nome VARCHAR(20) NOT NULL,
	Email VARCHAR(20) NOT NULL,
	Senha VARCHAR(20) NOT NULL,
	Permissão VARCHAR(20) NOT NULL
)

CREATE TABLE Albuns
(
	IdAlbum INT PRIMARY KEY IDENTITY,
	IdArtista INT FOREIGN KEY REFERENCES Artistas(IdArtista) NOT NULL,
	Titulo VARCHAR(20) NOT NULL,
	DataLancamento VARCHAR(20) NOT NULL,
	Localizacao VARCHAR(20) NOT NULL,
	QtdMinutos VARCHAR(20) NOT NULL,
	Ativo VARCHAR(3) NOT NULL
)	

CREATE TABLE AlbunsEstilos
(
	IdAlbum INT FOREIGN KEY REFERENCES Albuns(IdAlbum) NOT NULL,
	IdEstilo INT FOREIGN KEY REFERENCES Estilos(IdEstilo) NOT NULL,
)



-- CONFERIR A TABELA
SELECT * FROM Artistas
SELECT * FROM Albuns
SELECT * FROM Usuarios
SELECT * FROM AlbunsEstilos
SELECT * FROM Estilos






