-- DDL

-- CRIAR UM BANCO
CREATE DATABASE Exercicio_1_2;

-- USAR O BANCO CRIADO
USE Exercicio_1_2;

-- CRIAR TABELAS
-- UNIQUE ( CAMPO EXCLUSIVO QUE NÃO PODE SER REPETIDO. EX: CPF, CNH, EMAIL ).
-- NOT NULL ( CAMPO QUE DEVE SER PREENCHIDO OBRIGATORIAMENTE ).
CREATE TABLE Cliente
(
	IdCliente INT PRIMARY KEY IDENTITY,
	Nome VARCHAR(20) NOT NULL,
	CPF VARCHAR(11) NOT NULL UNIQUE
)

CREATE TABLE Modelo
(
	IdModelo INT PRIMARY KEY IDENTITY,
	Nome VARCHAR(20) NOT NULL
)

CREATE TABLE Empresa
(
	IdEmpresa INT PRIMARY KEY IDENTITY,
	Nome VARCHAR(20) NOT NULL
)

CREATE TABLE Marca
(
	IdMarca INT PRIMARY KEY IDENTITY,
	Nome VARCHAR(20) NOT NULL
)

CREATE TABLE Veiculo
(
	IdVeiculo INT PRIMARY KEY IDENTITY,
	IdEmpresa INT FOREIGN KEY REFERENCES Empresa(IdEmpresa) NOT NULL,
	IdModelo INT FOREIGN KEY REFERENCES Modelo(IdModelo) NOT NULL,
	IdMarca INT FOREIGN KEY REFERENCES Marca(IdMarca) NOT NULL,
	Placa VARCHAR(10) NOT NULL
)

CREATE TABLE Aluguel
(
	IdAluguel INT PRIMARY KEY IDENTITY,
	IdVeiculo INT FOREIGN KEY REFERENCES Veiculo(IdVeiculo) NOT NULL,
	IdCliente INT FOREIGN KEY REFERENCES Cliente(IdCliente) NOT NULL,
	Protocolo VARCHAR(20) NOT NULL
)

-- CONFERIR A TABELA
SELECT * FROM Cliente
SELECT * FROM Modelo
SELECT * FROM Empresa
SELECT * FROM Marca
SELECT * FROM Veiculo
SELECT * FROM Aluguel



